version: '3.7'
services:
  api:
    build: ./api
    container_name: api
    restart:  always
    ports: 
      - 8080:8080
    depends_on: 
      - db
  db:
    image: mariadb
    container_name: db
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=root 
    volumes: 
      - ./db:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports: 
      - 9000:8080
    depends_on: 
      - db